import React from 'react'
import {render,screen,fireEvent} from '@testing-library/react'
import TemplatesPrototype from '@/app/[locale]/(dashboard)/templates/TemplatesPrototype'
jest.mock('next-intl',()=>({useLocale:()=> 'en'}))
describe('Templates editor',()=>{
 beforeEach(()=>sessionStorage.clear())
 test('adds and removes editable cards without affecting other slides; undo restores',()=>{
  render(<TemplatesPrototype startInEditor />)
  fireEvent.click(screen.getByRole('button',{name:'3 slides'}))
  fireEvent.click(screen.getByRole('button',{name:'Add text card'}))
  fireEvent.change(screen.getByLabelText('Card text'),{target:{value:'My optional card'}})
  fireEvent.click(screen.getByRole('button',{name:'Select slide 2'}))
  expect(screen.queryByRole('button',{name:'Edit text card 3'})).not.toBeInTheDocument()
  fireEvent.click(screen.getByRole('button',{name:'Select slide 1'}))
  fireEvent.click(screen.getByRole('button',{name:'Edit text card 3'}))
  expect(screen.getByLabelText('Card text')).toHaveValue('My optional card')
  fireEvent.click(screen.getByRole('button',{name:'Remove card'}))
  expect(screen.queryByRole('button',{name:'Edit text card 3'})).not.toBeInTheDocument()
  fireEvent.click(screen.getByRole('button',{name:'Undo'}))
  expect(screen.getByRole('button',{name:'Edit text card 3'})).toBeInTheDocument()
 })
 test('card styles, removal and labels survive saving and reopening',()=>{
  const view=render(<TemplatesPrototype startInEditor />)
  fireEvent.change(screen.getByLabelText('Card text'),{target:{value:'Saved card'}})
  fireEvent.change(screen.getByLabelText('Card style'),{target:{value:'plain'}})
  fireEvent.change(screen.getByLabelText('Header label (empty to hide)'),{target:{value:''}})
  fireEvent.click(screen.getByRole('button',{name:'Save draft'}));view.unmount()
  render(<TemplatesPrototype startInEditor />)
  expect(screen.getByLabelText('Card text')).toHaveValue('Saved card')
  expect(screen.getByLabelText('Card style')).toHaveValue('plain')
  expect(screen.queryByText('PEOPLE & STORIES')).not.toBeInTheDocument()
 })
 test('cancels stale count confirmation when current count is chosen',()=>{
  render(<TemplatesPrototype startInEditor />)
  fireEvent.click(screen.getByRole('button',{name:'4 slides'}))
  fireEvent.click(screen.getByRole('button',{name:'1 slide'}))
  expect(screen.getByRole('button',{name:'Reduce slides'})).toBeInTheDocument()
  fireEvent.click(screen.getByRole('button',{name:'4 slides'}))
  expect(screen.queryByRole('button',{name:'Reduce slides'})).not.toBeInTheDocument()
  expect(screen.getByRole('button',{name:'Select slide 4'})).toBeInTheDocument()
 })
 test('supports zero text cards and keeps publishing disabled',()=>{
  render(<TemplatesPrototype startInEditor />)
  fireEvent.click(screen.getByRole('button',{name:'Remove card'}))
  fireEvent.click(screen.getByRole('button',{name:'Remove card'}))
  expect(screen.queryByLabelText('Card text')).not.toBeInTheDocument()
  fireEvent.click(screen.getByRole('button',{name:'Review slides'}))
  expect(screen.getByRole('button',{name:'Create post (coming later)'})).toBeDisabled()
 })
 test('typography applies per card and survives draft restoration',()=>{
  const view=render(<TemplatesPrototype startInEditor />)
  fireEvent.change(screen.getByLabelText('Font family'),{target:{value:'serif'}})
  for(const name of ['Bold','Italic','Underline'])fireEvent.click(screen.getByRole('button',{name}))
  fireEvent.change(screen.getByLabelText('Exact text size'),{target:{value:'4.75'}})
  fireEvent.change(screen.getByLabelText('Line height'),{target:{value:'2'}})
  fireEvent.change(screen.getByLabelText('Letter spacing (em)'),{target:{value:'0.1'}})
  const preview=screen.getByRole('button',{name:'Edit text card 1'})
  expect(preview).toHaveStyle({fontWeight:'700',fontStyle:'italic',textDecoration:'underline',lineHeight:'2',letterSpacing:'0.1em'})
  expect(screen.getByLabelText('Exact text size')).toHaveValue(4.75)
  expect(screen.getByRole('button',{name:'Edit text card 2'}).style.fontStyle).toBe('normal')
  fireEvent.click(screen.getByRole('button',{name:'Save draft'}));view.unmount()
  render(<TemplatesPrototype startInEditor />)
  expect(screen.getByLabelText('Font family')).toHaveValue('serif')
  expect(screen.getByLabelText('Exact text size')).toHaveValue(4.75)
  expect(screen.getByRole('button',{name:'Bold'})).toHaveAttribute('aria-pressed','true')
  expect(screen.getByLabelText('Line height')).toHaveValue(2)
  expect(screen.getByLabelText('Letter spacing (em)')).toHaveValue(0.1)
 })
 test('presets preserve content and geometry and are undoable',()=>{
  render(<TemplatesPrototype startInEditor />)
  const text=(screen.getByLabelText('Card text') as HTMLTextAreaElement).value
  fireEvent.click(screen.getByRole('button',{name:'Caption'}))
  expect(screen.getByLabelText('Exact text size')).toHaveValue(2.75)
  expect(screen.getByLabelText('Card text')).toHaveValue(text)
  expect(screen.getByRole('button',{name:'Edit text card 1'}).style.width).toBe('')
  fireEvent.click(screen.getByRole('button',{name:'Undo'}))
  expect(screen.getByLabelText('Exact text size')).toHaveValue(5.2)
  fireEvent.change(screen.getByLabelText('Exact text size'),{target:{value:'99'}})
  expect(screen.getByLabelText('Exact text size')).toHaveValue(5.2)
 })

 test('inline multiline editing commits once, remains scoped to card, and supports undo',()=>{
  render(<TemplatesPrototype startInEditor />)
  const first=screen.getByRole('button',{name:'Edit text card 1'})
  const original=first.textContent
  fireEvent.click(first)
  expect(screen.getByRole('region',{name:'Selected card tools'})).toBeInTheDocument()
  fireEvent.doubleClick(first)
  const editor=screen.getByRole('textbox',{name:'Card text on canvas'})
  fireEvent.change(editor,{target:{value:'Japanese 日本語\nSecond line'}})
  fireEvent.blur(editor)
  expect(screen.queryByRole('textbox',{name:'Card text on canvas'})).not.toBeInTheDocument()
  expect(screen.getByRole('button',{name:'Edit text card 1'}).textContent).toBe('Japanese 日本語\nSecond line')
  expect(screen.getByRole('button',{name:'Edit text card 2'}).textContent).not.toContain('Japanese')
  fireEvent.click(screen.getByRole('button',{name:'Undo'}))
  expect(screen.getByRole('button',{name:'Edit text card 1'}).textContent).toBe(original)
 })
 test('context toolbar updates selection and exposes actions without opening inspector',()=>{
  render(<TemplatesPrototype startInEditor />)
  fireEvent.click(screen.getByRole('button',{name:'Edit text card 1'}))
  fireEvent.click(screen.getByRole('button',{name:'Quick bold'}))
  expect(screen.getByRole('button',{name:'Edit text card 1'})).toHaveStyle({fontWeight:'700'})
  fireEvent.click(screen.getByRole('button',{name:'More'}))
  fireEvent.click(screen.getByRole('button',{name:'Copy card'}))
  expect(screen.getByRole('button',{name:'Edit text card 3'})).toBeInTheDocument()
  fireEvent.click(screen.getByRole('button',{name:'Deselect card'}))
  expect(screen.queryByRole('region',{name:'Selected card tools'})).not.toBeInTheDocument()
 })

 test('clicking blank canvas saves inline edits before deselecting',()=>{
  render(<TemplatesPrototype startInEditor />)
  fireEvent.doubleClick(screen.getByRole('button',{name:'Edit text card 1'}))
  fireEvent.change(screen.getByRole('textbox',{name:'Card text on canvas'}),{target:{value:'Keep this edit'}})
  fireEvent.click(screen.getByRole('region',{name:'Live preview'}))
  expect(screen.getByRole('button',{name:'Edit text card 1'}).textContent).toBe('Keep this edit')
  expect(screen.queryByRole('region',{name:'Selected card tools'})).not.toBeInTheDocument()
 })

 test('shape selection survives saving and direct deletion is undoable',()=>{
  const view=render(<TemplatesPrototype startInEditor />)
  fireEvent.click(screen.getByRole('button',{name:'Edit text card 1'}))
  const original=screen.getByRole('button',{name:'Edit text card 1'}).textContent
  fireEvent.click(screen.getByRole('button',{name:'Shapes'}))
  for(const name of ['Rectangle','Pill','Oval','Organic bubble','Arch','Text only','Rounded']){
   fireEvent.click(screen.getByRole('button',{name}))
   expect(screen.getByRole('button',{name:'Edit text card 1'}).textContent).toBe(original)
  }
  fireEvent.click(screen.getByRole('button',{name:'Arch'}))
  fireEvent.click(screen.getByRole('button',{name:'Save draft'}));view.unmount()
  render(<TemplatesPrototype startInEditor />)
  expect(screen.getByLabelText('Card style')).toHaveValue('arch')
  fireEvent.click(screen.getByRole('button',{name:'Edit text card 1'}))
  fireEvent.click(screen.getByRole('button',{name:'Delete selected card'}))
  expect(screen.queryByRole('button',{name:'Edit text card 2'})).not.toBeInTheDocument()
  fireEvent.click(screen.getByRole('button',{name:'Undo'}))
  expect(screen.getByRole('button',{name:'Edit text card 1'}).textContent).toBe(original)
  expect(screen.getByRole('button',{name:'Edit text card 2'})).toBeInTheDocument()
 })

 test('supports every slide count through ten and restores ten-slide drafts',()=>{
  const view=render(<TemplatesPrototype startInEditor />)
  for(let n=1;n<=10;n++)expect(screen.getByRole('button',{name:`${n} ${n===1?'slide':'slides'}`})).toBeInTheDocument()
  fireEvent.click(screen.getByRole('button',{name:'10 slides'}))
  expect(screen.getByRole('button',{name:'Select slide 10'})).toBeInTheDocument()
  expect(screen.getByRole('button',{name:'Duplicate'})).toBeDisabled()
  fireEvent.click(screen.getByRole('button',{name:'Save draft'}));view.unmount()
  render(<TemplatesPrototype startInEditor />)
  expect(screen.getByRole('button',{name:'Select slide 10'})).toBeInTheDocument()
  fireEvent.click(screen.getByRole('button',{name:'2 slides'}))
  fireEvent.click(screen.getByRole('button',{name:'Reduce slides'}))
  expect(screen.queryByRole('button',{name:'Select slide 3'})).not.toBeInTheDocument()
 })

})
