
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ConnectedAccount` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ConnectedAccount
 * 
 */
export type ConnectedAccountModel = runtime.Types.Result.DefaultSelection<Prisma.$ConnectedAccountPayload>

export type AggregateConnectedAccount = {
  _count: ConnectedAccountCountAggregateOutputType | null
  _min: ConnectedAccountMinAggregateOutputType | null
  _max: ConnectedAccountMaxAggregateOutputType | null
}

export type ConnectedAccountMinAggregateOutputType = {
  id: string | null
  userId: string | null
  facebookUserId: string | null
  pageId: string | null
  pageAccessToken: string | null
  instagramBusinessId: string | null
  longLivedUserToken: string | null
  tokenExpiry: Date | null
  createdAt: Date | null
}

export type ConnectedAccountMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  facebookUserId: string | null
  pageId: string | null
  pageAccessToken: string | null
  instagramBusinessId: string | null
  longLivedUserToken: string | null
  tokenExpiry: Date | null
  createdAt: Date | null
}

export type ConnectedAccountCountAggregateOutputType = {
  id: number
  userId: number
  facebookUserId: number
  pageId: number
  pageAccessToken: number
  instagramBusinessId: number
  longLivedUserToken: number
  tokenExpiry: number
  createdAt: number
  _all: number
}


export type ConnectedAccountMinAggregateInputType = {
  id?: true
  userId?: true
  facebookUserId?: true
  pageId?: true
  pageAccessToken?: true
  instagramBusinessId?: true
  longLivedUserToken?: true
  tokenExpiry?: true
  createdAt?: true
}

export type ConnectedAccountMaxAggregateInputType = {
  id?: true
  userId?: true
  facebookUserId?: true
  pageId?: true
  pageAccessToken?: true
  instagramBusinessId?: true
  longLivedUserToken?: true
  tokenExpiry?: true
  createdAt?: true
}

export type ConnectedAccountCountAggregateInputType = {
  id?: true
  userId?: true
  facebookUserId?: true
  pageId?: true
  pageAccessToken?: true
  instagramBusinessId?: true
  longLivedUserToken?: true
  tokenExpiry?: true
  createdAt?: true
  _all?: true
}

export type ConnectedAccountAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ConnectedAccount to aggregate.
   */
  where?: Prisma.ConnectedAccountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ConnectedAccounts to fetch.
   */
  orderBy?: Prisma.ConnectedAccountOrderByWithRelationInput | Prisma.ConnectedAccountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ConnectedAccountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ConnectedAccounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ConnectedAccounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ConnectedAccounts
  **/
  _count?: true | ConnectedAccountCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ConnectedAccountMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ConnectedAccountMaxAggregateInputType
}

export type GetConnectedAccountAggregateType<T extends ConnectedAccountAggregateArgs> = {
      [P in keyof T & keyof AggregateConnectedAccount]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateConnectedAccount[P]>
    : Prisma.GetScalarType<T[P], AggregateConnectedAccount[P]>
}




export type ConnectedAccountGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ConnectedAccountWhereInput
  orderBy?: Prisma.ConnectedAccountOrderByWithAggregationInput | Prisma.ConnectedAccountOrderByWithAggregationInput[]
  by: Prisma.ConnectedAccountScalarFieldEnum[] | Prisma.ConnectedAccountScalarFieldEnum
  having?: Prisma.ConnectedAccountScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ConnectedAccountCountAggregateInputType | true
  _min?: ConnectedAccountMinAggregateInputType
  _max?: ConnectedAccountMaxAggregateInputType
}

export type ConnectedAccountGroupByOutputType = {
  id: string
  userId: string
  facebookUserId: string
  pageId: string
  pageAccessToken: string
  instagramBusinessId: string
  longLivedUserToken: string
  tokenExpiry: Date
  createdAt: Date
  _count: ConnectedAccountCountAggregateOutputType | null
  _min: ConnectedAccountMinAggregateOutputType | null
  _max: ConnectedAccountMaxAggregateOutputType | null
}

type GetConnectedAccountGroupByPayload<T extends ConnectedAccountGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ConnectedAccountGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ConnectedAccountGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ConnectedAccountGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ConnectedAccountGroupByOutputType[P]>
      }
    >
  >



export type ConnectedAccountWhereInput = {
  AND?: Prisma.ConnectedAccountWhereInput | Prisma.ConnectedAccountWhereInput[]
  OR?: Prisma.ConnectedAccountWhereInput[]
  NOT?: Prisma.ConnectedAccountWhereInput | Prisma.ConnectedAccountWhereInput[]
  id?: Prisma.StringFilter<"ConnectedAccount"> | string
  userId?: Prisma.StringFilter<"ConnectedAccount"> | string
  facebookUserId?: Prisma.StringFilter<"ConnectedAccount"> | string
  pageId?: Prisma.StringFilter<"ConnectedAccount"> | string
  pageAccessToken?: Prisma.StringFilter<"ConnectedAccount"> | string
  instagramBusinessId?: Prisma.StringFilter<"ConnectedAccount"> | string
  longLivedUserToken?: Prisma.StringFilter<"ConnectedAccount"> | string
  tokenExpiry?: Prisma.DateTimeFilter<"ConnectedAccount"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"ConnectedAccount"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  posts?: Prisma.PostListRelationFilter
}

export type ConnectedAccountOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  facebookUserId?: Prisma.SortOrder
  pageId?: Prisma.SortOrder
  pageAccessToken?: Prisma.SortOrder
  instagramBusinessId?: Prisma.SortOrder
  longLivedUserToken?: Prisma.SortOrder
  tokenExpiry?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  posts?: Prisma.PostOrderByRelationAggregateInput
}

export type ConnectedAccountWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId_pageId?: Prisma.ConnectedAccountUserIdPageIdCompoundUniqueInput
  AND?: Prisma.ConnectedAccountWhereInput | Prisma.ConnectedAccountWhereInput[]
  OR?: Prisma.ConnectedAccountWhereInput[]
  NOT?: Prisma.ConnectedAccountWhereInput | Prisma.ConnectedAccountWhereInput[]
  userId?: Prisma.StringFilter<"ConnectedAccount"> | string
  facebookUserId?: Prisma.StringFilter<"ConnectedAccount"> | string
  pageId?: Prisma.StringFilter<"ConnectedAccount"> | string
  pageAccessToken?: Prisma.StringFilter<"ConnectedAccount"> | string
  instagramBusinessId?: Prisma.StringFilter<"ConnectedAccount"> | string
  longLivedUserToken?: Prisma.StringFilter<"ConnectedAccount"> | string
  tokenExpiry?: Prisma.DateTimeFilter<"ConnectedAccount"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"ConnectedAccount"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  posts?: Prisma.PostListRelationFilter
}, "id" | "userId_pageId">

export type ConnectedAccountOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  facebookUserId?: Prisma.SortOrder
  pageId?: Prisma.SortOrder
  pageAccessToken?: Prisma.SortOrder
  instagramBusinessId?: Prisma.SortOrder
  longLivedUserToken?: Prisma.SortOrder
  tokenExpiry?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.ConnectedAccountCountOrderByAggregateInput
  _max?: Prisma.ConnectedAccountMaxOrderByAggregateInput
  _min?: Prisma.ConnectedAccountMinOrderByAggregateInput
}

export type ConnectedAccountScalarWhereWithAggregatesInput = {
  AND?: Prisma.ConnectedAccountScalarWhereWithAggregatesInput | Prisma.ConnectedAccountScalarWhereWithAggregatesInput[]
  OR?: Prisma.ConnectedAccountScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ConnectedAccountScalarWhereWithAggregatesInput | Prisma.ConnectedAccountScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ConnectedAccount"> | string
  userId?: Prisma.StringWithAggregatesFilter<"ConnectedAccount"> | string
  facebookUserId?: Prisma.StringWithAggregatesFilter<"ConnectedAccount"> | string
  pageId?: Prisma.StringWithAggregatesFilter<"ConnectedAccount"> | string
  pageAccessToken?: Prisma.StringWithAggregatesFilter<"ConnectedAccount"> | string
  instagramBusinessId?: Prisma.StringWithAggregatesFilter<"ConnectedAccount"> | string
  longLivedUserToken?: Prisma.StringWithAggregatesFilter<"ConnectedAccount"> | string
  tokenExpiry?: Prisma.DateTimeWithAggregatesFilter<"ConnectedAccount"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ConnectedAccount"> | Date | string
}

export type ConnectedAccountCreateInput = {
  id?: string
  facebookUserId: string
  pageId: string
  pageAccessToken: string
  instagramBusinessId: string
  longLivedUserToken: string
  tokenExpiry: Date | string
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutConnectedAccountsInput
  posts?: Prisma.PostCreateNestedManyWithoutConnectedAccountInput
}

export type ConnectedAccountUncheckedCreateInput = {
  id?: string
  userId: string
  facebookUserId: string
  pageId: string
  pageAccessToken: string
  instagramBusinessId: string
  longLivedUserToken: string
  tokenExpiry: Date | string
  createdAt?: Date | string
  posts?: Prisma.PostUncheckedCreateNestedManyWithoutConnectedAccountInput
}

export type ConnectedAccountUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  facebookUserId?: Prisma.StringFieldUpdateOperationsInput | string
  pageId?: Prisma.StringFieldUpdateOperationsInput | string
  pageAccessToken?: Prisma.StringFieldUpdateOperationsInput | string
  instagramBusinessId?: Prisma.StringFieldUpdateOperationsInput | string
  longLivedUserToken?: Prisma.StringFieldUpdateOperationsInput | string
  tokenExpiry?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutConnectedAccountsNestedInput
  posts?: Prisma.PostUpdateManyWithoutConnectedAccountNestedInput
}

export type ConnectedAccountUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  facebookUserId?: Prisma.StringFieldUpdateOperationsInput | string
  pageId?: Prisma.StringFieldUpdateOperationsInput | string
  pageAccessToken?: Prisma.StringFieldUpdateOperationsInput | string
  instagramBusinessId?: Prisma.StringFieldUpdateOperationsInput | string
  longLivedUserToken?: Prisma.StringFieldUpdateOperationsInput | string
  tokenExpiry?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  posts?: Prisma.PostUncheckedUpdateManyWithoutConnectedAccountNestedInput
}

export type ConnectedAccountCreateManyInput = {
  id?: string
  userId: string
  facebookUserId: string
  pageId: string
  pageAccessToken: string
  instagramBusinessId: string
  longLivedUserToken: string
  tokenExpiry: Date | string
  createdAt?: Date | string
}

export type ConnectedAccountUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  facebookUserId?: Prisma.StringFieldUpdateOperationsInput | string
  pageId?: Prisma.StringFieldUpdateOperationsInput | string
  pageAccessToken?: Prisma.StringFieldUpdateOperationsInput | string
  instagramBusinessId?: Prisma.StringFieldUpdateOperationsInput | string
  longLivedUserToken?: Prisma.StringFieldUpdateOperationsInput | string
  tokenExpiry?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ConnectedAccountUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  facebookUserId?: Prisma.StringFieldUpdateOperationsInput | string
  pageId?: Prisma.StringFieldUpdateOperationsInput | string
  pageAccessToken?: Prisma.StringFieldUpdateOperationsInput | string
  instagramBusinessId?: Prisma.StringFieldUpdateOperationsInput | string
  longLivedUserToken?: Prisma.StringFieldUpdateOperationsInput | string
  tokenExpiry?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ConnectedAccountListRelationFilter = {
  every?: Prisma.ConnectedAccountWhereInput
  some?: Prisma.ConnectedAccountWhereInput
  none?: Prisma.ConnectedAccountWhereInput
}

export type ConnectedAccountOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ConnectedAccountUserIdPageIdCompoundUniqueInput = {
  userId: string
  pageId: string
}

export type ConnectedAccountCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  facebookUserId?: Prisma.SortOrder
  pageId?: Prisma.SortOrder
  pageAccessToken?: Prisma.SortOrder
  instagramBusinessId?: Prisma.SortOrder
  longLivedUserToken?: Prisma.SortOrder
  tokenExpiry?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ConnectedAccountMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  facebookUserId?: Prisma.SortOrder
  pageId?: Prisma.SortOrder
  pageAccessToken?: Prisma.SortOrder
  instagramBusinessId?: Prisma.SortOrder
  longLivedUserToken?: Prisma.SortOrder
  tokenExpiry?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ConnectedAccountMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  facebookUserId?: Prisma.SortOrder
  pageId?: Prisma.SortOrder
  pageAccessToken?: Prisma.SortOrder
  instagramBusinessId?: Prisma.SortOrder
  longLivedUserToken?: Prisma.SortOrder
  tokenExpiry?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ConnectedAccountScalarRelationFilter = {
  is?: Prisma.ConnectedAccountWhereInput
  isNot?: Prisma.ConnectedAccountWhereInput
}

export type ConnectedAccountCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ConnectedAccountCreateWithoutUserInput, Prisma.ConnectedAccountUncheckedCreateWithoutUserInput> | Prisma.ConnectedAccountCreateWithoutUserInput[] | Prisma.ConnectedAccountUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ConnectedAccountCreateOrConnectWithoutUserInput | Prisma.ConnectedAccountCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ConnectedAccountCreateManyUserInputEnvelope
  connect?: Prisma.ConnectedAccountWhereUniqueInput | Prisma.ConnectedAccountWhereUniqueInput[]
}

export type ConnectedAccountUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ConnectedAccountCreateWithoutUserInput, Prisma.ConnectedAccountUncheckedCreateWithoutUserInput> | Prisma.ConnectedAccountCreateWithoutUserInput[] | Prisma.ConnectedAccountUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ConnectedAccountCreateOrConnectWithoutUserInput | Prisma.ConnectedAccountCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ConnectedAccountCreateManyUserInputEnvelope
  connect?: Prisma.ConnectedAccountWhereUniqueInput | Prisma.ConnectedAccountWhereUniqueInput[]
}

export type ConnectedAccountUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ConnectedAccountCreateWithoutUserInput, Prisma.ConnectedAccountUncheckedCreateWithoutUserInput> | Prisma.ConnectedAccountCreateWithoutUserInput[] | Prisma.ConnectedAccountUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ConnectedAccountCreateOrConnectWithoutUserInput | Prisma.ConnectedAccountCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ConnectedAccountUpsertWithWhereUniqueWithoutUserInput | Prisma.ConnectedAccountUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ConnectedAccountCreateManyUserInputEnvelope
  set?: Prisma.ConnectedAccountWhereUniqueInput | Prisma.ConnectedAccountWhereUniqueInput[]
  disconnect?: Prisma.ConnectedAccountWhereUniqueInput | Prisma.ConnectedAccountWhereUniqueInput[]
  delete?: Prisma.ConnectedAccountWhereUniqueInput | Prisma.ConnectedAccountWhereUniqueInput[]
  connect?: Prisma.ConnectedAccountWhereUniqueInput | Prisma.ConnectedAccountWhereUniqueInput[]
  update?: Prisma.ConnectedAccountUpdateWithWhereUniqueWithoutUserInput | Prisma.ConnectedAccountUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ConnectedAccountUpdateManyWithWhereWithoutUserInput | Prisma.ConnectedAccountUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ConnectedAccountScalarWhereInput | Prisma.ConnectedAccountScalarWhereInput[]
}

export type ConnectedAccountUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ConnectedAccountCreateWithoutUserInput, Prisma.ConnectedAccountUncheckedCreateWithoutUserInput> | Prisma.ConnectedAccountCreateWithoutUserInput[] | Prisma.ConnectedAccountUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ConnectedAccountCreateOrConnectWithoutUserInput | Prisma.ConnectedAccountCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ConnectedAccountUpsertWithWhereUniqueWithoutUserInput | Prisma.ConnectedAccountUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ConnectedAccountCreateManyUserInputEnvelope
  set?: Prisma.ConnectedAccountWhereUniqueInput | Prisma.ConnectedAccountWhereUniqueInput[]
  disconnect?: Prisma.ConnectedAccountWhereUniqueInput | Prisma.ConnectedAccountWhereUniqueInput[]
  delete?: Prisma.ConnectedAccountWhereUniqueInput | Prisma.ConnectedAccountWhereUniqueInput[]
  connect?: Prisma.ConnectedAccountWhereUniqueInput | Prisma.ConnectedAccountWhereUniqueInput[]
  update?: Prisma.ConnectedAccountUpdateWithWhereUniqueWithoutUserInput | Prisma.ConnectedAccountUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ConnectedAccountUpdateManyWithWhereWithoutUserInput | Prisma.ConnectedAccountUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ConnectedAccountScalarWhereInput | Prisma.ConnectedAccountScalarWhereInput[]
}

export type ConnectedAccountCreateNestedOneWithoutPostsInput = {
  create?: Prisma.XOR<Prisma.ConnectedAccountCreateWithoutPostsInput, Prisma.ConnectedAccountUncheckedCreateWithoutPostsInput>
  connectOrCreate?: Prisma.ConnectedAccountCreateOrConnectWithoutPostsInput
  connect?: Prisma.ConnectedAccountWhereUniqueInput
}

export type ConnectedAccountUpdateOneRequiredWithoutPostsNestedInput = {
  create?: Prisma.XOR<Prisma.ConnectedAccountCreateWithoutPostsInput, Prisma.ConnectedAccountUncheckedCreateWithoutPostsInput>
  connectOrCreate?: Prisma.ConnectedAccountCreateOrConnectWithoutPostsInput
  upsert?: Prisma.ConnectedAccountUpsertWithoutPostsInput
  connect?: Prisma.ConnectedAccountWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ConnectedAccountUpdateToOneWithWhereWithoutPostsInput, Prisma.ConnectedAccountUpdateWithoutPostsInput>, Prisma.ConnectedAccountUncheckedUpdateWithoutPostsInput>
}

export type ConnectedAccountCreateWithoutUserInput = {
  id?: string
  facebookUserId: string
  pageId: string
  pageAccessToken: string
  instagramBusinessId: string
  longLivedUserToken: string
  tokenExpiry: Date | string
  createdAt?: Date | string
  posts?: Prisma.PostCreateNestedManyWithoutConnectedAccountInput
}

export type ConnectedAccountUncheckedCreateWithoutUserInput = {
  id?: string
  facebookUserId: string
  pageId: string
  pageAccessToken: string
  instagramBusinessId: string
  longLivedUserToken: string
  tokenExpiry: Date | string
  createdAt?: Date | string
  posts?: Prisma.PostUncheckedCreateNestedManyWithoutConnectedAccountInput
}

export type ConnectedAccountCreateOrConnectWithoutUserInput = {
  where: Prisma.ConnectedAccountWhereUniqueInput
  create: Prisma.XOR<Prisma.ConnectedAccountCreateWithoutUserInput, Prisma.ConnectedAccountUncheckedCreateWithoutUserInput>
}

export type ConnectedAccountCreateManyUserInputEnvelope = {
  data: Prisma.ConnectedAccountCreateManyUserInput | Prisma.ConnectedAccountCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type ConnectedAccountUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.ConnectedAccountWhereUniqueInput
  update: Prisma.XOR<Prisma.ConnectedAccountUpdateWithoutUserInput, Prisma.ConnectedAccountUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.ConnectedAccountCreateWithoutUserInput, Prisma.ConnectedAccountUncheckedCreateWithoutUserInput>
}

export type ConnectedAccountUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.ConnectedAccountWhereUniqueInput
  data: Prisma.XOR<Prisma.ConnectedAccountUpdateWithoutUserInput, Prisma.ConnectedAccountUncheckedUpdateWithoutUserInput>
}

export type ConnectedAccountUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.ConnectedAccountScalarWhereInput
  data: Prisma.XOR<Prisma.ConnectedAccountUpdateManyMutationInput, Prisma.ConnectedAccountUncheckedUpdateManyWithoutUserInput>
}

export type ConnectedAccountScalarWhereInput = {
  AND?: Prisma.ConnectedAccountScalarWhereInput | Prisma.ConnectedAccountScalarWhereInput[]
  OR?: Prisma.ConnectedAccountScalarWhereInput[]
  NOT?: Prisma.ConnectedAccountScalarWhereInput | Prisma.ConnectedAccountScalarWhereInput[]
  id?: Prisma.StringFilter<"ConnectedAccount"> | string
  userId?: Prisma.StringFilter<"ConnectedAccount"> | string
  facebookUserId?: Prisma.StringFilter<"ConnectedAccount"> | string
  pageId?: Prisma.StringFilter<"ConnectedAccount"> | string
  pageAccessToken?: Prisma.StringFilter<"ConnectedAccount"> | string
  instagramBusinessId?: Prisma.StringFilter<"ConnectedAccount"> | string
  longLivedUserToken?: Prisma.StringFilter<"ConnectedAccount"> | string
  tokenExpiry?: Prisma.DateTimeFilter<"ConnectedAccount"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"ConnectedAccount"> | Date | string
}

export type ConnectedAccountCreateWithoutPostsInput = {
  id?: string
  facebookUserId: string
  pageId: string
  pageAccessToken: string
  instagramBusinessId: string
  longLivedUserToken: string
  tokenExpiry: Date | string
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutConnectedAccountsInput
}

export type ConnectedAccountUncheckedCreateWithoutPostsInput = {
  id?: string
  userId: string
  facebookUserId: string
  pageId: string
  pageAccessToken: string
  instagramBusinessId: string
  longLivedUserToken: string
  tokenExpiry: Date | string
  createdAt?: Date | string
}

export type ConnectedAccountCreateOrConnectWithoutPostsInput = {
  where: Prisma.ConnectedAccountWhereUniqueInput
  create: Prisma.XOR<Prisma.ConnectedAccountCreateWithoutPostsInput, Prisma.ConnectedAccountUncheckedCreateWithoutPostsInput>
}

export type ConnectedAccountUpsertWithoutPostsInput = {
  update: Prisma.XOR<Prisma.ConnectedAccountUpdateWithoutPostsInput, Prisma.ConnectedAccountUncheckedUpdateWithoutPostsInput>
  create: Prisma.XOR<Prisma.ConnectedAccountCreateWithoutPostsInput, Prisma.ConnectedAccountUncheckedCreateWithoutPostsInput>
  where?: Prisma.ConnectedAccountWhereInput
}

export type ConnectedAccountUpdateToOneWithWhereWithoutPostsInput = {
  where?: Prisma.ConnectedAccountWhereInput
  data: Prisma.XOR<Prisma.ConnectedAccountUpdateWithoutPostsInput, Prisma.ConnectedAccountUncheckedUpdateWithoutPostsInput>
}

export type ConnectedAccountUpdateWithoutPostsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  facebookUserId?: Prisma.StringFieldUpdateOperationsInput | string
  pageId?: Prisma.StringFieldUpdateOperationsInput | string
  pageAccessToken?: Prisma.StringFieldUpdateOperationsInput | string
  instagramBusinessId?: Prisma.StringFieldUpdateOperationsInput | string
  longLivedUserToken?: Prisma.StringFieldUpdateOperationsInput | string
  tokenExpiry?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutConnectedAccountsNestedInput
}

export type ConnectedAccountUncheckedUpdateWithoutPostsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  facebookUserId?: Prisma.StringFieldUpdateOperationsInput | string
  pageId?: Prisma.StringFieldUpdateOperationsInput | string
  pageAccessToken?: Prisma.StringFieldUpdateOperationsInput | string
  instagramBusinessId?: Prisma.StringFieldUpdateOperationsInput | string
  longLivedUserToken?: Prisma.StringFieldUpdateOperationsInput | string
  tokenExpiry?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ConnectedAccountCreateManyUserInput = {
  id?: string
  facebookUserId: string
  pageId: string
  pageAccessToken: string
  instagramBusinessId: string
  longLivedUserToken: string
  tokenExpiry: Date | string
  createdAt?: Date | string
}

export type ConnectedAccountUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  facebookUserId?: Prisma.StringFieldUpdateOperationsInput | string
  pageId?: Prisma.StringFieldUpdateOperationsInput | string
  pageAccessToken?: Prisma.StringFieldUpdateOperationsInput | string
  instagramBusinessId?: Prisma.StringFieldUpdateOperationsInput | string
  longLivedUserToken?: Prisma.StringFieldUpdateOperationsInput | string
  tokenExpiry?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  posts?: Prisma.PostUpdateManyWithoutConnectedAccountNestedInput
}

export type ConnectedAccountUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  facebookUserId?: Prisma.StringFieldUpdateOperationsInput | string
  pageId?: Prisma.StringFieldUpdateOperationsInput | string
  pageAccessToken?: Prisma.StringFieldUpdateOperationsInput | string
  instagramBusinessId?: Prisma.StringFieldUpdateOperationsInput | string
  longLivedUserToken?: Prisma.StringFieldUpdateOperationsInput | string
  tokenExpiry?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  posts?: Prisma.PostUncheckedUpdateManyWithoutConnectedAccountNestedInput
}

export type ConnectedAccountUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  facebookUserId?: Prisma.StringFieldUpdateOperationsInput | string
  pageId?: Prisma.StringFieldUpdateOperationsInput | string
  pageAccessToken?: Prisma.StringFieldUpdateOperationsInput | string
  instagramBusinessId?: Prisma.StringFieldUpdateOperationsInput | string
  longLivedUserToken?: Prisma.StringFieldUpdateOperationsInput | string
  tokenExpiry?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type ConnectedAccountCountOutputType
 */

export type ConnectedAccountCountOutputType = {
  posts: number
}

export type ConnectedAccountCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  posts?: boolean | ConnectedAccountCountOutputTypeCountPostsArgs
}

/**
 * ConnectedAccountCountOutputType without action
 */
export type ConnectedAccountCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConnectedAccountCountOutputType
   */
  select?: Prisma.ConnectedAccountCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ConnectedAccountCountOutputType without action
 */
export type ConnectedAccountCountOutputTypeCountPostsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PostWhereInput
}


export type ConnectedAccountSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  facebookUserId?: boolean
  pageId?: boolean
  pageAccessToken?: boolean
  instagramBusinessId?: boolean
  longLivedUserToken?: boolean
  tokenExpiry?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  posts?: boolean | Prisma.ConnectedAccount$postsArgs<ExtArgs>
  _count?: boolean | Prisma.ConnectedAccountCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["connectedAccount"]>

export type ConnectedAccountSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  facebookUserId?: boolean
  pageId?: boolean
  pageAccessToken?: boolean
  instagramBusinessId?: boolean
  longLivedUserToken?: boolean
  tokenExpiry?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["connectedAccount"]>

export type ConnectedAccountSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  facebookUserId?: boolean
  pageId?: boolean
  pageAccessToken?: boolean
  instagramBusinessId?: boolean
  longLivedUserToken?: boolean
  tokenExpiry?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["connectedAccount"]>

export type ConnectedAccountSelectScalar = {
  id?: boolean
  userId?: boolean
  facebookUserId?: boolean
  pageId?: boolean
  pageAccessToken?: boolean
  instagramBusinessId?: boolean
  longLivedUserToken?: boolean
  tokenExpiry?: boolean
  createdAt?: boolean
}

export type ConnectedAccountOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "facebookUserId" | "pageId" | "pageAccessToken" | "instagramBusinessId" | "longLivedUserToken" | "tokenExpiry" | "createdAt", ExtArgs["result"]["connectedAccount"]>
export type ConnectedAccountInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  posts?: boolean | Prisma.ConnectedAccount$postsArgs<ExtArgs>
  _count?: boolean | Prisma.ConnectedAccountCountOutputTypeDefaultArgs<ExtArgs>
}
export type ConnectedAccountIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type ConnectedAccountIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $ConnectedAccountPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ConnectedAccount"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    posts: Prisma.$PostPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    facebookUserId: string
    pageId: string
    pageAccessToken: string
    instagramBusinessId: string
    longLivedUserToken: string
    tokenExpiry: Date
    createdAt: Date
  }, ExtArgs["result"]["connectedAccount"]>
  composites: {}
}

export type ConnectedAccountGetPayload<S extends boolean | null | undefined | ConnectedAccountDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ConnectedAccountPayload, S>

export type ConnectedAccountCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ConnectedAccountFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ConnectedAccountCountAggregateInputType | true
  }

export interface ConnectedAccountDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ConnectedAccount'], meta: { name: 'ConnectedAccount' } }
  /**
   * Find zero or one ConnectedAccount that matches the filter.
   * @param {ConnectedAccountFindUniqueArgs} args - Arguments to find a ConnectedAccount
   * @example
   * // Get one ConnectedAccount
   * const connectedAccount = await prisma.connectedAccount.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ConnectedAccountFindUniqueArgs>(args: Prisma.SelectSubset<T, ConnectedAccountFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ConnectedAccountClient<runtime.Types.Result.GetResult<Prisma.$ConnectedAccountPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ConnectedAccount that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ConnectedAccountFindUniqueOrThrowArgs} args - Arguments to find a ConnectedAccount
   * @example
   * // Get one ConnectedAccount
   * const connectedAccount = await prisma.connectedAccount.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ConnectedAccountFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ConnectedAccountFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ConnectedAccountClient<runtime.Types.Result.GetResult<Prisma.$ConnectedAccountPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ConnectedAccount that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConnectedAccountFindFirstArgs} args - Arguments to find a ConnectedAccount
   * @example
   * // Get one ConnectedAccount
   * const connectedAccount = await prisma.connectedAccount.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ConnectedAccountFindFirstArgs>(args?: Prisma.SelectSubset<T, ConnectedAccountFindFirstArgs<ExtArgs>>): Prisma.Prisma__ConnectedAccountClient<runtime.Types.Result.GetResult<Prisma.$ConnectedAccountPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ConnectedAccount that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConnectedAccountFindFirstOrThrowArgs} args - Arguments to find a ConnectedAccount
   * @example
   * // Get one ConnectedAccount
   * const connectedAccount = await prisma.connectedAccount.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ConnectedAccountFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ConnectedAccountFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ConnectedAccountClient<runtime.Types.Result.GetResult<Prisma.$ConnectedAccountPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ConnectedAccounts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConnectedAccountFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ConnectedAccounts
   * const connectedAccounts = await prisma.connectedAccount.findMany()
   * 
   * // Get first 10 ConnectedAccounts
   * const connectedAccounts = await prisma.connectedAccount.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const connectedAccountWithIdOnly = await prisma.connectedAccount.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ConnectedAccountFindManyArgs>(args?: Prisma.SelectSubset<T, ConnectedAccountFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ConnectedAccountPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ConnectedAccount.
   * @param {ConnectedAccountCreateArgs} args - Arguments to create a ConnectedAccount.
   * @example
   * // Create one ConnectedAccount
   * const ConnectedAccount = await prisma.connectedAccount.create({
   *   data: {
   *     // ... data to create a ConnectedAccount
   *   }
   * })
   * 
   */
  create<T extends ConnectedAccountCreateArgs>(args: Prisma.SelectSubset<T, ConnectedAccountCreateArgs<ExtArgs>>): Prisma.Prisma__ConnectedAccountClient<runtime.Types.Result.GetResult<Prisma.$ConnectedAccountPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ConnectedAccounts.
   * @param {ConnectedAccountCreateManyArgs} args - Arguments to create many ConnectedAccounts.
   * @example
   * // Create many ConnectedAccounts
   * const connectedAccount = await prisma.connectedAccount.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ConnectedAccountCreateManyArgs>(args?: Prisma.SelectSubset<T, ConnectedAccountCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ConnectedAccounts and returns the data saved in the database.
   * @param {ConnectedAccountCreateManyAndReturnArgs} args - Arguments to create many ConnectedAccounts.
   * @example
   * // Create many ConnectedAccounts
   * const connectedAccount = await prisma.connectedAccount.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ConnectedAccounts and only return the `id`
   * const connectedAccountWithIdOnly = await prisma.connectedAccount.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ConnectedAccountCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ConnectedAccountCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ConnectedAccountPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ConnectedAccount.
   * @param {ConnectedAccountDeleteArgs} args - Arguments to delete one ConnectedAccount.
   * @example
   * // Delete one ConnectedAccount
   * const ConnectedAccount = await prisma.connectedAccount.delete({
   *   where: {
   *     // ... filter to delete one ConnectedAccount
   *   }
   * })
   * 
   */
  delete<T extends ConnectedAccountDeleteArgs>(args: Prisma.SelectSubset<T, ConnectedAccountDeleteArgs<ExtArgs>>): Prisma.Prisma__ConnectedAccountClient<runtime.Types.Result.GetResult<Prisma.$ConnectedAccountPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ConnectedAccount.
   * @param {ConnectedAccountUpdateArgs} args - Arguments to update one ConnectedAccount.
   * @example
   * // Update one ConnectedAccount
   * const connectedAccount = await prisma.connectedAccount.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ConnectedAccountUpdateArgs>(args: Prisma.SelectSubset<T, ConnectedAccountUpdateArgs<ExtArgs>>): Prisma.Prisma__ConnectedAccountClient<runtime.Types.Result.GetResult<Prisma.$ConnectedAccountPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ConnectedAccounts.
   * @param {ConnectedAccountDeleteManyArgs} args - Arguments to filter ConnectedAccounts to delete.
   * @example
   * // Delete a few ConnectedAccounts
   * const { count } = await prisma.connectedAccount.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ConnectedAccountDeleteManyArgs>(args?: Prisma.SelectSubset<T, ConnectedAccountDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ConnectedAccounts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConnectedAccountUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ConnectedAccounts
   * const connectedAccount = await prisma.connectedAccount.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ConnectedAccountUpdateManyArgs>(args: Prisma.SelectSubset<T, ConnectedAccountUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ConnectedAccounts and returns the data updated in the database.
   * @param {ConnectedAccountUpdateManyAndReturnArgs} args - Arguments to update many ConnectedAccounts.
   * @example
   * // Update many ConnectedAccounts
   * const connectedAccount = await prisma.connectedAccount.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ConnectedAccounts and only return the `id`
   * const connectedAccountWithIdOnly = await prisma.connectedAccount.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ConnectedAccountUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ConnectedAccountUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ConnectedAccountPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ConnectedAccount.
   * @param {ConnectedAccountUpsertArgs} args - Arguments to update or create a ConnectedAccount.
   * @example
   * // Update or create a ConnectedAccount
   * const connectedAccount = await prisma.connectedAccount.upsert({
   *   create: {
   *     // ... data to create a ConnectedAccount
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ConnectedAccount we want to update
   *   }
   * })
   */
  upsert<T extends ConnectedAccountUpsertArgs>(args: Prisma.SelectSubset<T, ConnectedAccountUpsertArgs<ExtArgs>>): Prisma.Prisma__ConnectedAccountClient<runtime.Types.Result.GetResult<Prisma.$ConnectedAccountPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ConnectedAccounts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConnectedAccountCountArgs} args - Arguments to filter ConnectedAccounts to count.
   * @example
   * // Count the number of ConnectedAccounts
   * const count = await prisma.connectedAccount.count({
   *   where: {
   *     // ... the filter for the ConnectedAccounts we want to count
   *   }
   * })
  **/
  count<T extends ConnectedAccountCountArgs>(
    args?: Prisma.Subset<T, ConnectedAccountCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ConnectedAccountCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ConnectedAccount.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConnectedAccountAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ConnectedAccountAggregateArgs>(args: Prisma.Subset<T, ConnectedAccountAggregateArgs>): Prisma.PrismaPromise<GetConnectedAccountAggregateType<T>>

  /**
   * Group by ConnectedAccount.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConnectedAccountGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ConnectedAccountGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ConnectedAccountGroupByArgs['orderBy'] }
      : { orderBy?: ConnectedAccountGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ConnectedAccountGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetConnectedAccountGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ConnectedAccount model
 */
readonly fields: ConnectedAccountFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ConnectedAccount.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ConnectedAccountClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  posts<T extends Prisma.ConnectedAccount$postsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ConnectedAccount$postsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PostPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ConnectedAccount model
 */
export interface ConnectedAccountFieldRefs {
  readonly id: Prisma.FieldRef<"ConnectedAccount", 'String'>
  readonly userId: Prisma.FieldRef<"ConnectedAccount", 'String'>
  readonly facebookUserId: Prisma.FieldRef<"ConnectedAccount", 'String'>
  readonly pageId: Prisma.FieldRef<"ConnectedAccount", 'String'>
  readonly pageAccessToken: Prisma.FieldRef<"ConnectedAccount", 'String'>
  readonly instagramBusinessId: Prisma.FieldRef<"ConnectedAccount", 'String'>
  readonly longLivedUserToken: Prisma.FieldRef<"ConnectedAccount", 'String'>
  readonly tokenExpiry: Prisma.FieldRef<"ConnectedAccount", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"ConnectedAccount", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ConnectedAccount findUnique
 */
export type ConnectedAccountFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConnectedAccount
   */
  select?: Prisma.ConnectedAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConnectedAccount
   */
  omit?: Prisma.ConnectedAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConnectedAccountInclude<ExtArgs> | null
  /**
   * Filter, which ConnectedAccount to fetch.
   */
  where: Prisma.ConnectedAccountWhereUniqueInput
}

/**
 * ConnectedAccount findUniqueOrThrow
 */
export type ConnectedAccountFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConnectedAccount
   */
  select?: Prisma.ConnectedAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConnectedAccount
   */
  omit?: Prisma.ConnectedAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConnectedAccountInclude<ExtArgs> | null
  /**
   * Filter, which ConnectedAccount to fetch.
   */
  where: Prisma.ConnectedAccountWhereUniqueInput
}

/**
 * ConnectedAccount findFirst
 */
export type ConnectedAccountFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConnectedAccount
   */
  select?: Prisma.ConnectedAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConnectedAccount
   */
  omit?: Prisma.ConnectedAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConnectedAccountInclude<ExtArgs> | null
  /**
   * Filter, which ConnectedAccount to fetch.
   */
  where?: Prisma.ConnectedAccountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ConnectedAccounts to fetch.
   */
  orderBy?: Prisma.ConnectedAccountOrderByWithRelationInput | Prisma.ConnectedAccountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ConnectedAccounts.
   */
  cursor?: Prisma.ConnectedAccountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ConnectedAccounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ConnectedAccounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ConnectedAccounts.
   */
  distinct?: Prisma.ConnectedAccountScalarFieldEnum | Prisma.ConnectedAccountScalarFieldEnum[]
}

/**
 * ConnectedAccount findFirstOrThrow
 */
export type ConnectedAccountFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConnectedAccount
   */
  select?: Prisma.ConnectedAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConnectedAccount
   */
  omit?: Prisma.ConnectedAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConnectedAccountInclude<ExtArgs> | null
  /**
   * Filter, which ConnectedAccount to fetch.
   */
  where?: Prisma.ConnectedAccountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ConnectedAccounts to fetch.
   */
  orderBy?: Prisma.ConnectedAccountOrderByWithRelationInput | Prisma.ConnectedAccountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ConnectedAccounts.
   */
  cursor?: Prisma.ConnectedAccountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ConnectedAccounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ConnectedAccounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ConnectedAccounts.
   */
  distinct?: Prisma.ConnectedAccountScalarFieldEnum | Prisma.ConnectedAccountScalarFieldEnum[]
}

/**
 * ConnectedAccount findMany
 */
export type ConnectedAccountFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConnectedAccount
   */
  select?: Prisma.ConnectedAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConnectedAccount
   */
  omit?: Prisma.ConnectedAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConnectedAccountInclude<ExtArgs> | null
  /**
   * Filter, which ConnectedAccounts to fetch.
   */
  where?: Prisma.ConnectedAccountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ConnectedAccounts to fetch.
   */
  orderBy?: Prisma.ConnectedAccountOrderByWithRelationInput | Prisma.ConnectedAccountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ConnectedAccounts.
   */
  cursor?: Prisma.ConnectedAccountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ConnectedAccounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ConnectedAccounts.
   */
  skip?: number
  distinct?: Prisma.ConnectedAccountScalarFieldEnum | Prisma.ConnectedAccountScalarFieldEnum[]
}

/**
 * ConnectedAccount create
 */
export type ConnectedAccountCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConnectedAccount
   */
  select?: Prisma.ConnectedAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConnectedAccount
   */
  omit?: Prisma.ConnectedAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConnectedAccountInclude<ExtArgs> | null
  /**
   * The data needed to create a ConnectedAccount.
   */
  data: Prisma.XOR<Prisma.ConnectedAccountCreateInput, Prisma.ConnectedAccountUncheckedCreateInput>
}

/**
 * ConnectedAccount createMany
 */
export type ConnectedAccountCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ConnectedAccounts.
   */
  data: Prisma.ConnectedAccountCreateManyInput | Prisma.ConnectedAccountCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ConnectedAccount createManyAndReturn
 */
export type ConnectedAccountCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConnectedAccount
   */
  select?: Prisma.ConnectedAccountSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ConnectedAccount
   */
  omit?: Prisma.ConnectedAccountOmit<ExtArgs> | null
  /**
   * The data used to create many ConnectedAccounts.
   */
  data: Prisma.ConnectedAccountCreateManyInput | Prisma.ConnectedAccountCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConnectedAccountIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ConnectedAccount update
 */
export type ConnectedAccountUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConnectedAccount
   */
  select?: Prisma.ConnectedAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConnectedAccount
   */
  omit?: Prisma.ConnectedAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConnectedAccountInclude<ExtArgs> | null
  /**
   * The data needed to update a ConnectedAccount.
   */
  data: Prisma.XOR<Prisma.ConnectedAccountUpdateInput, Prisma.ConnectedAccountUncheckedUpdateInput>
  /**
   * Choose, which ConnectedAccount to update.
   */
  where: Prisma.ConnectedAccountWhereUniqueInput
}

/**
 * ConnectedAccount updateMany
 */
export type ConnectedAccountUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ConnectedAccounts.
   */
  data: Prisma.XOR<Prisma.ConnectedAccountUpdateManyMutationInput, Prisma.ConnectedAccountUncheckedUpdateManyInput>
  /**
   * Filter which ConnectedAccounts to update
   */
  where?: Prisma.ConnectedAccountWhereInput
  /**
   * Limit how many ConnectedAccounts to update.
   */
  limit?: number
}

/**
 * ConnectedAccount updateManyAndReturn
 */
export type ConnectedAccountUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConnectedAccount
   */
  select?: Prisma.ConnectedAccountSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ConnectedAccount
   */
  omit?: Prisma.ConnectedAccountOmit<ExtArgs> | null
  /**
   * The data used to update ConnectedAccounts.
   */
  data: Prisma.XOR<Prisma.ConnectedAccountUpdateManyMutationInput, Prisma.ConnectedAccountUncheckedUpdateManyInput>
  /**
   * Filter which ConnectedAccounts to update
   */
  where?: Prisma.ConnectedAccountWhereInput
  /**
   * Limit how many ConnectedAccounts to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConnectedAccountIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ConnectedAccount upsert
 */
export type ConnectedAccountUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConnectedAccount
   */
  select?: Prisma.ConnectedAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConnectedAccount
   */
  omit?: Prisma.ConnectedAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConnectedAccountInclude<ExtArgs> | null
  /**
   * The filter to search for the ConnectedAccount to update in case it exists.
   */
  where: Prisma.ConnectedAccountWhereUniqueInput
  /**
   * In case the ConnectedAccount found by the `where` argument doesn't exist, create a new ConnectedAccount with this data.
   */
  create: Prisma.XOR<Prisma.ConnectedAccountCreateInput, Prisma.ConnectedAccountUncheckedCreateInput>
  /**
   * In case the ConnectedAccount was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ConnectedAccountUpdateInput, Prisma.ConnectedAccountUncheckedUpdateInput>
}

/**
 * ConnectedAccount delete
 */
export type ConnectedAccountDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConnectedAccount
   */
  select?: Prisma.ConnectedAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConnectedAccount
   */
  omit?: Prisma.ConnectedAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConnectedAccountInclude<ExtArgs> | null
  /**
   * Filter which ConnectedAccount to delete.
   */
  where: Prisma.ConnectedAccountWhereUniqueInput
}

/**
 * ConnectedAccount deleteMany
 */
export type ConnectedAccountDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ConnectedAccounts to delete
   */
  where?: Prisma.ConnectedAccountWhereInput
  /**
   * Limit how many ConnectedAccounts to delete.
   */
  limit?: number
}

/**
 * ConnectedAccount.posts
 */
export type ConnectedAccount$postsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Post
   */
  select?: Prisma.PostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Post
   */
  omit?: Prisma.PostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostInclude<ExtArgs> | null
  where?: Prisma.PostWhereInput
  orderBy?: Prisma.PostOrderByWithRelationInput | Prisma.PostOrderByWithRelationInput[]
  cursor?: Prisma.PostWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PostScalarFieldEnum | Prisma.PostScalarFieldEnum[]
}

/**
 * ConnectedAccount without action
 */
export type ConnectedAccountDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConnectedAccount
   */
  select?: Prisma.ConnectedAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConnectedAccount
   */
  omit?: Prisma.ConnectedAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConnectedAccountInclude<ExtArgs> | null
}
