
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `InstagramAccount` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model InstagramAccount
 * 
 */
export type InstagramAccountModel = runtime.Types.Result.DefaultSelection<Prisma.$InstagramAccountPayload>

export type AggregateInstagramAccount = {
  _count: InstagramAccountCountAggregateOutputType | null
  _min: InstagramAccountMinAggregateOutputType | null
  _max: InstagramAccountMaxAggregateOutputType | null
}

export type InstagramAccountMinAggregateOutputType = {
  id: string | null
  userId: string | null
  username: string | null
  password: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type InstagramAccountMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  username: string | null
  password: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type InstagramAccountCountAggregateOutputType = {
  id: number
  userId: number
  username: number
  password: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type InstagramAccountMinAggregateInputType = {
  id?: true
  userId?: true
  username?: true
  password?: true
  createdAt?: true
  updatedAt?: true
}

export type InstagramAccountMaxAggregateInputType = {
  id?: true
  userId?: true
  username?: true
  password?: true
  createdAt?: true
  updatedAt?: true
}

export type InstagramAccountCountAggregateInputType = {
  id?: true
  userId?: true
  username?: true
  password?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type InstagramAccountAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which InstagramAccount to aggregate.
   */
  where?: Prisma.InstagramAccountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InstagramAccounts to fetch.
   */
  orderBy?: Prisma.InstagramAccountOrderByWithRelationInput | Prisma.InstagramAccountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.InstagramAccountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InstagramAccounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InstagramAccounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned InstagramAccounts
  **/
  _count?: true | InstagramAccountCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: InstagramAccountMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: InstagramAccountMaxAggregateInputType
}

export type GetInstagramAccountAggregateType<T extends InstagramAccountAggregateArgs> = {
      [P in keyof T & keyof AggregateInstagramAccount]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateInstagramAccount[P]>
    : Prisma.GetScalarType<T[P], AggregateInstagramAccount[P]>
}




export type InstagramAccountGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.InstagramAccountWhereInput
  orderBy?: Prisma.InstagramAccountOrderByWithAggregationInput | Prisma.InstagramAccountOrderByWithAggregationInput[]
  by: Prisma.InstagramAccountScalarFieldEnum[] | Prisma.InstagramAccountScalarFieldEnum
  having?: Prisma.InstagramAccountScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: InstagramAccountCountAggregateInputType | true
  _min?: InstagramAccountMinAggregateInputType
  _max?: InstagramAccountMaxAggregateInputType
}

export type InstagramAccountGroupByOutputType = {
  id: string
  userId: string
  username: string
  password: string | null
  createdAt: Date
  updatedAt: Date
  _count: InstagramAccountCountAggregateOutputType | null
  _min: InstagramAccountMinAggregateOutputType | null
  _max: InstagramAccountMaxAggregateOutputType | null
}

type GetInstagramAccountGroupByPayload<T extends InstagramAccountGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<InstagramAccountGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof InstagramAccountGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], InstagramAccountGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], InstagramAccountGroupByOutputType[P]>
      }
    >
  >



export type InstagramAccountWhereInput = {
  AND?: Prisma.InstagramAccountWhereInput | Prisma.InstagramAccountWhereInput[]
  OR?: Prisma.InstagramAccountWhereInput[]
  NOT?: Prisma.InstagramAccountWhereInput | Prisma.InstagramAccountWhereInput[]
  id?: Prisma.StringFilter<"InstagramAccount"> | string
  userId?: Prisma.StringFilter<"InstagramAccount"> | string
  username?: Prisma.StringFilter<"InstagramAccount"> | string
  password?: Prisma.StringNullableFilter<"InstagramAccount"> | string | null
  createdAt?: Prisma.DateTimeFilter<"InstagramAccount"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"InstagramAccount"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type InstagramAccountOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  username?: Prisma.SortOrder
  password?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type InstagramAccountWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId_username?: Prisma.InstagramAccountUserIdUsernameCompoundUniqueInput
  AND?: Prisma.InstagramAccountWhereInput | Prisma.InstagramAccountWhereInput[]
  OR?: Prisma.InstagramAccountWhereInput[]
  NOT?: Prisma.InstagramAccountWhereInput | Prisma.InstagramAccountWhereInput[]
  userId?: Prisma.StringFilter<"InstagramAccount"> | string
  username?: Prisma.StringFilter<"InstagramAccount"> | string
  password?: Prisma.StringNullableFilter<"InstagramAccount"> | string | null
  createdAt?: Prisma.DateTimeFilter<"InstagramAccount"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"InstagramAccount"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "userId_username">

export type InstagramAccountOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  username?: Prisma.SortOrder
  password?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.InstagramAccountCountOrderByAggregateInput
  _max?: Prisma.InstagramAccountMaxOrderByAggregateInput
  _min?: Prisma.InstagramAccountMinOrderByAggregateInput
}

export type InstagramAccountScalarWhereWithAggregatesInput = {
  AND?: Prisma.InstagramAccountScalarWhereWithAggregatesInput | Prisma.InstagramAccountScalarWhereWithAggregatesInput[]
  OR?: Prisma.InstagramAccountScalarWhereWithAggregatesInput[]
  NOT?: Prisma.InstagramAccountScalarWhereWithAggregatesInput | Prisma.InstagramAccountScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"InstagramAccount"> | string
  userId?: Prisma.StringWithAggregatesFilter<"InstagramAccount"> | string
  username?: Prisma.StringWithAggregatesFilter<"InstagramAccount"> | string
  password?: Prisma.StringNullableWithAggregatesFilter<"InstagramAccount"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"InstagramAccount"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"InstagramAccount"> | Date | string
}

export type InstagramAccountCreateInput = {
  id?: string
  username: string
  password?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutInstagramAccountsInput
}

export type InstagramAccountUncheckedCreateInput = {
  id?: string
  userId: string
  username: string
  password?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type InstagramAccountUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutInstagramAccountsNestedInput
}

export type InstagramAccountUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InstagramAccountCreateManyInput = {
  id?: string
  userId: string
  username: string
  password?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type InstagramAccountUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InstagramAccountUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InstagramAccountListRelationFilter = {
  every?: Prisma.InstagramAccountWhereInput
  some?: Prisma.InstagramAccountWhereInput
  none?: Prisma.InstagramAccountWhereInput
}

export type InstagramAccountOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type InstagramAccountUserIdUsernameCompoundUniqueInput = {
  userId: string
  username: string
}

export type InstagramAccountCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  username?: Prisma.SortOrder
  password?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type InstagramAccountMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  username?: Prisma.SortOrder
  password?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type InstagramAccountMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  username?: Prisma.SortOrder
  password?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type InstagramAccountCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.InstagramAccountCreateWithoutUserInput, Prisma.InstagramAccountUncheckedCreateWithoutUserInput> | Prisma.InstagramAccountCreateWithoutUserInput[] | Prisma.InstagramAccountUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.InstagramAccountCreateOrConnectWithoutUserInput | Prisma.InstagramAccountCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.InstagramAccountCreateManyUserInputEnvelope
  connect?: Prisma.InstagramAccountWhereUniqueInput | Prisma.InstagramAccountWhereUniqueInput[]
}

export type InstagramAccountUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.InstagramAccountCreateWithoutUserInput, Prisma.InstagramAccountUncheckedCreateWithoutUserInput> | Prisma.InstagramAccountCreateWithoutUserInput[] | Prisma.InstagramAccountUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.InstagramAccountCreateOrConnectWithoutUserInput | Prisma.InstagramAccountCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.InstagramAccountCreateManyUserInputEnvelope
  connect?: Prisma.InstagramAccountWhereUniqueInput | Prisma.InstagramAccountWhereUniqueInput[]
}

export type InstagramAccountUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.InstagramAccountCreateWithoutUserInput, Prisma.InstagramAccountUncheckedCreateWithoutUserInput> | Prisma.InstagramAccountCreateWithoutUserInput[] | Prisma.InstagramAccountUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.InstagramAccountCreateOrConnectWithoutUserInput | Prisma.InstagramAccountCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.InstagramAccountUpsertWithWhereUniqueWithoutUserInput | Prisma.InstagramAccountUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.InstagramAccountCreateManyUserInputEnvelope
  set?: Prisma.InstagramAccountWhereUniqueInput | Prisma.InstagramAccountWhereUniqueInput[]
  disconnect?: Prisma.InstagramAccountWhereUniqueInput | Prisma.InstagramAccountWhereUniqueInput[]
  delete?: Prisma.InstagramAccountWhereUniqueInput | Prisma.InstagramAccountWhereUniqueInput[]
  connect?: Prisma.InstagramAccountWhereUniqueInput | Prisma.InstagramAccountWhereUniqueInput[]
  update?: Prisma.InstagramAccountUpdateWithWhereUniqueWithoutUserInput | Prisma.InstagramAccountUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.InstagramAccountUpdateManyWithWhereWithoutUserInput | Prisma.InstagramAccountUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.InstagramAccountScalarWhereInput | Prisma.InstagramAccountScalarWhereInput[]
}

export type InstagramAccountUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.InstagramAccountCreateWithoutUserInput, Prisma.InstagramAccountUncheckedCreateWithoutUserInput> | Prisma.InstagramAccountCreateWithoutUserInput[] | Prisma.InstagramAccountUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.InstagramAccountCreateOrConnectWithoutUserInput | Prisma.InstagramAccountCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.InstagramAccountUpsertWithWhereUniqueWithoutUserInput | Prisma.InstagramAccountUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.InstagramAccountCreateManyUserInputEnvelope
  set?: Prisma.InstagramAccountWhereUniqueInput | Prisma.InstagramAccountWhereUniqueInput[]
  disconnect?: Prisma.InstagramAccountWhereUniqueInput | Prisma.InstagramAccountWhereUniqueInput[]
  delete?: Prisma.InstagramAccountWhereUniqueInput | Prisma.InstagramAccountWhereUniqueInput[]
  connect?: Prisma.InstagramAccountWhereUniqueInput | Prisma.InstagramAccountWhereUniqueInput[]
  update?: Prisma.InstagramAccountUpdateWithWhereUniqueWithoutUserInput | Prisma.InstagramAccountUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.InstagramAccountUpdateManyWithWhereWithoutUserInput | Prisma.InstagramAccountUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.InstagramAccountScalarWhereInput | Prisma.InstagramAccountScalarWhereInput[]
}

export type InstagramAccountCreateWithoutUserInput = {
  id?: string
  username: string
  password?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type InstagramAccountUncheckedCreateWithoutUserInput = {
  id?: string
  username: string
  password?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type InstagramAccountCreateOrConnectWithoutUserInput = {
  where: Prisma.InstagramAccountWhereUniqueInput
  create: Prisma.XOR<Prisma.InstagramAccountCreateWithoutUserInput, Prisma.InstagramAccountUncheckedCreateWithoutUserInput>
}

export type InstagramAccountCreateManyUserInputEnvelope = {
  data: Prisma.InstagramAccountCreateManyUserInput | Prisma.InstagramAccountCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type InstagramAccountUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.InstagramAccountWhereUniqueInput
  update: Prisma.XOR<Prisma.InstagramAccountUpdateWithoutUserInput, Prisma.InstagramAccountUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.InstagramAccountCreateWithoutUserInput, Prisma.InstagramAccountUncheckedCreateWithoutUserInput>
}

export type InstagramAccountUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.InstagramAccountWhereUniqueInput
  data: Prisma.XOR<Prisma.InstagramAccountUpdateWithoutUserInput, Prisma.InstagramAccountUncheckedUpdateWithoutUserInput>
}

export type InstagramAccountUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.InstagramAccountScalarWhereInput
  data: Prisma.XOR<Prisma.InstagramAccountUpdateManyMutationInput, Prisma.InstagramAccountUncheckedUpdateManyWithoutUserInput>
}

export type InstagramAccountScalarWhereInput = {
  AND?: Prisma.InstagramAccountScalarWhereInput | Prisma.InstagramAccountScalarWhereInput[]
  OR?: Prisma.InstagramAccountScalarWhereInput[]
  NOT?: Prisma.InstagramAccountScalarWhereInput | Prisma.InstagramAccountScalarWhereInput[]
  id?: Prisma.StringFilter<"InstagramAccount"> | string
  userId?: Prisma.StringFilter<"InstagramAccount"> | string
  username?: Prisma.StringFilter<"InstagramAccount"> | string
  password?: Prisma.StringNullableFilter<"InstagramAccount"> | string | null
  createdAt?: Prisma.DateTimeFilter<"InstagramAccount"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"InstagramAccount"> | Date | string
}

export type InstagramAccountCreateManyUserInput = {
  id?: string
  username: string
  password?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type InstagramAccountUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InstagramAccountUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InstagramAccountUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type InstagramAccountSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  username?: boolean
  password?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["instagramAccount"]>

export type InstagramAccountSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  username?: boolean
  password?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["instagramAccount"]>

export type InstagramAccountSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  username?: boolean
  password?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["instagramAccount"]>

export type InstagramAccountSelectScalar = {
  id?: boolean
  userId?: boolean
  username?: boolean
  password?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type InstagramAccountOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "username" | "password" | "createdAt" | "updatedAt", ExtArgs["result"]["instagramAccount"]>
export type InstagramAccountInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type InstagramAccountIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type InstagramAccountIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $InstagramAccountPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "InstagramAccount"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    username: string
    password: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["instagramAccount"]>
  composites: {}
}

export type InstagramAccountGetPayload<S extends boolean | null | undefined | InstagramAccountDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$InstagramAccountPayload, S>

export type InstagramAccountCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<InstagramAccountFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: InstagramAccountCountAggregateInputType | true
  }

export interface InstagramAccountDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['InstagramAccount'], meta: { name: 'InstagramAccount' } }
  /**
   * Find zero or one InstagramAccount that matches the filter.
   * @param {InstagramAccountFindUniqueArgs} args - Arguments to find a InstagramAccount
   * @example
   * // Get one InstagramAccount
   * const instagramAccount = await prisma.instagramAccount.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends InstagramAccountFindUniqueArgs>(args: Prisma.SelectSubset<T, InstagramAccountFindUniqueArgs<ExtArgs>>): Prisma.Prisma__InstagramAccountClient<runtime.Types.Result.GetResult<Prisma.$InstagramAccountPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one InstagramAccount that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {InstagramAccountFindUniqueOrThrowArgs} args - Arguments to find a InstagramAccount
   * @example
   * // Get one InstagramAccount
   * const instagramAccount = await prisma.instagramAccount.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends InstagramAccountFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, InstagramAccountFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__InstagramAccountClient<runtime.Types.Result.GetResult<Prisma.$InstagramAccountPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first InstagramAccount that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InstagramAccountFindFirstArgs} args - Arguments to find a InstagramAccount
   * @example
   * // Get one InstagramAccount
   * const instagramAccount = await prisma.instagramAccount.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends InstagramAccountFindFirstArgs>(args?: Prisma.SelectSubset<T, InstagramAccountFindFirstArgs<ExtArgs>>): Prisma.Prisma__InstagramAccountClient<runtime.Types.Result.GetResult<Prisma.$InstagramAccountPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first InstagramAccount that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InstagramAccountFindFirstOrThrowArgs} args - Arguments to find a InstagramAccount
   * @example
   * // Get one InstagramAccount
   * const instagramAccount = await prisma.instagramAccount.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends InstagramAccountFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, InstagramAccountFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__InstagramAccountClient<runtime.Types.Result.GetResult<Prisma.$InstagramAccountPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more InstagramAccounts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InstagramAccountFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all InstagramAccounts
   * const instagramAccounts = await prisma.instagramAccount.findMany()
   * 
   * // Get first 10 InstagramAccounts
   * const instagramAccounts = await prisma.instagramAccount.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const instagramAccountWithIdOnly = await prisma.instagramAccount.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends InstagramAccountFindManyArgs>(args?: Prisma.SelectSubset<T, InstagramAccountFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InstagramAccountPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a InstagramAccount.
   * @param {InstagramAccountCreateArgs} args - Arguments to create a InstagramAccount.
   * @example
   * // Create one InstagramAccount
   * const InstagramAccount = await prisma.instagramAccount.create({
   *   data: {
   *     // ... data to create a InstagramAccount
   *   }
   * })
   * 
   */
  create<T extends InstagramAccountCreateArgs>(args: Prisma.SelectSubset<T, InstagramAccountCreateArgs<ExtArgs>>): Prisma.Prisma__InstagramAccountClient<runtime.Types.Result.GetResult<Prisma.$InstagramAccountPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many InstagramAccounts.
   * @param {InstagramAccountCreateManyArgs} args - Arguments to create many InstagramAccounts.
   * @example
   * // Create many InstagramAccounts
   * const instagramAccount = await prisma.instagramAccount.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends InstagramAccountCreateManyArgs>(args?: Prisma.SelectSubset<T, InstagramAccountCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many InstagramAccounts and returns the data saved in the database.
   * @param {InstagramAccountCreateManyAndReturnArgs} args - Arguments to create many InstagramAccounts.
   * @example
   * // Create many InstagramAccounts
   * const instagramAccount = await prisma.instagramAccount.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many InstagramAccounts and only return the `id`
   * const instagramAccountWithIdOnly = await prisma.instagramAccount.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends InstagramAccountCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, InstagramAccountCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InstagramAccountPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a InstagramAccount.
   * @param {InstagramAccountDeleteArgs} args - Arguments to delete one InstagramAccount.
   * @example
   * // Delete one InstagramAccount
   * const InstagramAccount = await prisma.instagramAccount.delete({
   *   where: {
   *     // ... filter to delete one InstagramAccount
   *   }
   * })
   * 
   */
  delete<T extends InstagramAccountDeleteArgs>(args: Prisma.SelectSubset<T, InstagramAccountDeleteArgs<ExtArgs>>): Prisma.Prisma__InstagramAccountClient<runtime.Types.Result.GetResult<Prisma.$InstagramAccountPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one InstagramAccount.
   * @param {InstagramAccountUpdateArgs} args - Arguments to update one InstagramAccount.
   * @example
   * // Update one InstagramAccount
   * const instagramAccount = await prisma.instagramAccount.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends InstagramAccountUpdateArgs>(args: Prisma.SelectSubset<T, InstagramAccountUpdateArgs<ExtArgs>>): Prisma.Prisma__InstagramAccountClient<runtime.Types.Result.GetResult<Prisma.$InstagramAccountPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more InstagramAccounts.
   * @param {InstagramAccountDeleteManyArgs} args - Arguments to filter InstagramAccounts to delete.
   * @example
   * // Delete a few InstagramAccounts
   * const { count } = await prisma.instagramAccount.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends InstagramAccountDeleteManyArgs>(args?: Prisma.SelectSubset<T, InstagramAccountDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more InstagramAccounts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InstagramAccountUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many InstagramAccounts
   * const instagramAccount = await prisma.instagramAccount.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends InstagramAccountUpdateManyArgs>(args: Prisma.SelectSubset<T, InstagramAccountUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more InstagramAccounts and returns the data updated in the database.
   * @param {InstagramAccountUpdateManyAndReturnArgs} args - Arguments to update many InstagramAccounts.
   * @example
   * // Update many InstagramAccounts
   * const instagramAccount = await prisma.instagramAccount.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more InstagramAccounts and only return the `id`
   * const instagramAccountWithIdOnly = await prisma.instagramAccount.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends InstagramAccountUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, InstagramAccountUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InstagramAccountPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one InstagramAccount.
   * @param {InstagramAccountUpsertArgs} args - Arguments to update or create a InstagramAccount.
   * @example
   * // Update or create a InstagramAccount
   * const instagramAccount = await prisma.instagramAccount.upsert({
   *   create: {
   *     // ... data to create a InstagramAccount
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the InstagramAccount we want to update
   *   }
   * })
   */
  upsert<T extends InstagramAccountUpsertArgs>(args: Prisma.SelectSubset<T, InstagramAccountUpsertArgs<ExtArgs>>): Prisma.Prisma__InstagramAccountClient<runtime.Types.Result.GetResult<Prisma.$InstagramAccountPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of InstagramAccounts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InstagramAccountCountArgs} args - Arguments to filter InstagramAccounts to count.
   * @example
   * // Count the number of InstagramAccounts
   * const count = await prisma.instagramAccount.count({
   *   where: {
   *     // ... the filter for the InstagramAccounts we want to count
   *   }
   * })
  **/
  count<T extends InstagramAccountCountArgs>(
    args?: Prisma.Subset<T, InstagramAccountCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], InstagramAccountCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a InstagramAccount.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InstagramAccountAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends InstagramAccountAggregateArgs>(args: Prisma.Subset<T, InstagramAccountAggregateArgs>): Prisma.PrismaPromise<GetInstagramAccountAggregateType<T>>

  /**
   * Group by InstagramAccount.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InstagramAccountGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends InstagramAccountGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: InstagramAccountGroupByArgs['orderBy'] }
      : { orderBy?: InstagramAccountGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, InstagramAccountGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetInstagramAccountGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the InstagramAccount model
 */
readonly fields: InstagramAccountFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for InstagramAccount.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__InstagramAccountClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the InstagramAccount model
 */
export interface InstagramAccountFieldRefs {
  readonly id: Prisma.FieldRef<"InstagramAccount", 'String'>
  readonly userId: Prisma.FieldRef<"InstagramAccount", 'String'>
  readonly username: Prisma.FieldRef<"InstagramAccount", 'String'>
  readonly password: Prisma.FieldRef<"InstagramAccount", 'String'>
  readonly createdAt: Prisma.FieldRef<"InstagramAccount", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"InstagramAccount", 'DateTime'>
}
    

// Custom InputTypes
/**
 * InstagramAccount findUnique
 */
export type InstagramAccountFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InstagramAccount
   */
  select?: Prisma.InstagramAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InstagramAccount
   */
  omit?: Prisma.InstagramAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InstagramAccountInclude<ExtArgs> | null
  /**
   * Filter, which InstagramAccount to fetch.
   */
  where: Prisma.InstagramAccountWhereUniqueInput
}

/**
 * InstagramAccount findUniqueOrThrow
 */
export type InstagramAccountFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InstagramAccount
   */
  select?: Prisma.InstagramAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InstagramAccount
   */
  omit?: Prisma.InstagramAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InstagramAccountInclude<ExtArgs> | null
  /**
   * Filter, which InstagramAccount to fetch.
   */
  where: Prisma.InstagramAccountWhereUniqueInput
}

/**
 * InstagramAccount findFirst
 */
export type InstagramAccountFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InstagramAccount
   */
  select?: Prisma.InstagramAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InstagramAccount
   */
  omit?: Prisma.InstagramAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InstagramAccountInclude<ExtArgs> | null
  /**
   * Filter, which InstagramAccount to fetch.
   */
  where?: Prisma.InstagramAccountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InstagramAccounts to fetch.
   */
  orderBy?: Prisma.InstagramAccountOrderByWithRelationInput | Prisma.InstagramAccountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for InstagramAccounts.
   */
  cursor?: Prisma.InstagramAccountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InstagramAccounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InstagramAccounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of InstagramAccounts.
   */
  distinct?: Prisma.InstagramAccountScalarFieldEnum | Prisma.InstagramAccountScalarFieldEnum[]
}

/**
 * InstagramAccount findFirstOrThrow
 */
export type InstagramAccountFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InstagramAccount
   */
  select?: Prisma.InstagramAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InstagramAccount
   */
  omit?: Prisma.InstagramAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InstagramAccountInclude<ExtArgs> | null
  /**
   * Filter, which InstagramAccount to fetch.
   */
  where?: Prisma.InstagramAccountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InstagramAccounts to fetch.
   */
  orderBy?: Prisma.InstagramAccountOrderByWithRelationInput | Prisma.InstagramAccountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for InstagramAccounts.
   */
  cursor?: Prisma.InstagramAccountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InstagramAccounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InstagramAccounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of InstagramAccounts.
   */
  distinct?: Prisma.InstagramAccountScalarFieldEnum | Prisma.InstagramAccountScalarFieldEnum[]
}

/**
 * InstagramAccount findMany
 */
export type InstagramAccountFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InstagramAccount
   */
  select?: Prisma.InstagramAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InstagramAccount
   */
  omit?: Prisma.InstagramAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InstagramAccountInclude<ExtArgs> | null
  /**
   * Filter, which InstagramAccounts to fetch.
   */
  where?: Prisma.InstagramAccountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InstagramAccounts to fetch.
   */
  orderBy?: Prisma.InstagramAccountOrderByWithRelationInput | Prisma.InstagramAccountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing InstagramAccounts.
   */
  cursor?: Prisma.InstagramAccountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InstagramAccounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InstagramAccounts.
   */
  skip?: number
  distinct?: Prisma.InstagramAccountScalarFieldEnum | Prisma.InstagramAccountScalarFieldEnum[]
}

/**
 * InstagramAccount create
 */
export type InstagramAccountCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InstagramAccount
   */
  select?: Prisma.InstagramAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InstagramAccount
   */
  omit?: Prisma.InstagramAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InstagramAccountInclude<ExtArgs> | null
  /**
   * The data needed to create a InstagramAccount.
   */
  data: Prisma.XOR<Prisma.InstagramAccountCreateInput, Prisma.InstagramAccountUncheckedCreateInput>
}

/**
 * InstagramAccount createMany
 */
export type InstagramAccountCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many InstagramAccounts.
   */
  data: Prisma.InstagramAccountCreateManyInput | Prisma.InstagramAccountCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * InstagramAccount createManyAndReturn
 */
export type InstagramAccountCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InstagramAccount
   */
  select?: Prisma.InstagramAccountSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the InstagramAccount
   */
  omit?: Prisma.InstagramAccountOmit<ExtArgs> | null
  /**
   * The data used to create many InstagramAccounts.
   */
  data: Prisma.InstagramAccountCreateManyInput | Prisma.InstagramAccountCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InstagramAccountIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * InstagramAccount update
 */
export type InstagramAccountUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InstagramAccount
   */
  select?: Prisma.InstagramAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InstagramAccount
   */
  omit?: Prisma.InstagramAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InstagramAccountInclude<ExtArgs> | null
  /**
   * The data needed to update a InstagramAccount.
   */
  data: Prisma.XOR<Prisma.InstagramAccountUpdateInput, Prisma.InstagramAccountUncheckedUpdateInput>
  /**
   * Choose, which InstagramAccount to update.
   */
  where: Prisma.InstagramAccountWhereUniqueInput
}

/**
 * InstagramAccount updateMany
 */
export type InstagramAccountUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update InstagramAccounts.
   */
  data: Prisma.XOR<Prisma.InstagramAccountUpdateManyMutationInput, Prisma.InstagramAccountUncheckedUpdateManyInput>
  /**
   * Filter which InstagramAccounts to update
   */
  where?: Prisma.InstagramAccountWhereInput
  /**
   * Limit how many InstagramAccounts to update.
   */
  limit?: number
}

/**
 * InstagramAccount updateManyAndReturn
 */
export type InstagramAccountUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InstagramAccount
   */
  select?: Prisma.InstagramAccountSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the InstagramAccount
   */
  omit?: Prisma.InstagramAccountOmit<ExtArgs> | null
  /**
   * The data used to update InstagramAccounts.
   */
  data: Prisma.XOR<Prisma.InstagramAccountUpdateManyMutationInput, Prisma.InstagramAccountUncheckedUpdateManyInput>
  /**
   * Filter which InstagramAccounts to update
   */
  where?: Prisma.InstagramAccountWhereInput
  /**
   * Limit how many InstagramAccounts to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InstagramAccountIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * InstagramAccount upsert
 */
export type InstagramAccountUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InstagramAccount
   */
  select?: Prisma.InstagramAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InstagramAccount
   */
  omit?: Prisma.InstagramAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InstagramAccountInclude<ExtArgs> | null
  /**
   * The filter to search for the InstagramAccount to update in case it exists.
   */
  where: Prisma.InstagramAccountWhereUniqueInput
  /**
   * In case the InstagramAccount found by the `where` argument doesn't exist, create a new InstagramAccount with this data.
   */
  create: Prisma.XOR<Prisma.InstagramAccountCreateInput, Prisma.InstagramAccountUncheckedCreateInput>
  /**
   * In case the InstagramAccount was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.InstagramAccountUpdateInput, Prisma.InstagramAccountUncheckedUpdateInput>
}

/**
 * InstagramAccount delete
 */
export type InstagramAccountDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InstagramAccount
   */
  select?: Prisma.InstagramAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InstagramAccount
   */
  omit?: Prisma.InstagramAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InstagramAccountInclude<ExtArgs> | null
  /**
   * Filter which InstagramAccount to delete.
   */
  where: Prisma.InstagramAccountWhereUniqueInput
}

/**
 * InstagramAccount deleteMany
 */
export type InstagramAccountDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which InstagramAccounts to delete
   */
  where?: Prisma.InstagramAccountWhereInput
  /**
   * Limit how many InstagramAccounts to delete.
   */
  limit?: number
}

/**
 * InstagramAccount without action
 */
export type InstagramAccountDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InstagramAccount
   */
  select?: Prisma.InstagramAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InstagramAccount
   */
  omit?: Prisma.InstagramAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InstagramAccountInclude<ExtArgs> | null
}
